function [opt] = dispatch(coeff_matrix,init_val,demand,epsilon,iter)
%Abhishek Malali 10EE07 NITK Surathkal 2014

%dispatch is a economic dispatch solver which uses gradient descent to
%converge to an optimal point.

%coeff_matrix describes the gradient of the cost function of the
%generators. It is of the form coeff_matrix = [0.0012    0.5;0.0010
%0.6;0.0014    0.4]. In this case there are 3 generators and their original
%equations were quadratic in nature.

%init_val is the initial value of the power generated by the generators.
%init_val in test case is[100;200;200]. All units are MW.

%demand is the total MW demand for which optimization is to be carried out
%for.Demand in test case is 500MW.

%epsilon is the scale used for handling the convergence.epsilon is 300 in
%test case.

%iter is the number of iterations.

no_gen = size(coeff_matrix,1);
no_parameters = size(coeff_matrix,2);
for j = 1:iter
p = repmat(init_val,1,no_parameters).^repmat([(no_parameters-1):-1:0],no_gen,1);
init_lambda = zeros(no_gen,1);
for i = 1:no_gen
 init_lambda(i,:) = sum(p(i,:).*(coeff_matrix(i,:)));
end
f = mean(init_lambda);
op_var = [init_val;f];
grad = init_lambda - f;
grad = [grad;demand - sum(init_val)];
op_var = op_var - epsilon*grad;
init_val = op_var(1:no_gen,:);
end
opt = init_val;
end

